### ISSUE TITLE
ajax modal not working 

### ISSUE THREAD

**Issue by cmanou** [dei79/jquery-modal-rails#11]
When you add :remote => true it just redirects you to the page and does not actually open up the modal

**Comment by blbradley** [comment]
I had this problem also. I used ':remote => true' in the form tag instead. My form returns a JSON response and prints flash messages based on that response. Let me know if you need to see an example.

**Comment by dhoss** [comment]
I'd like to see it.

**Comment by blbradley** [comment]
app/views/spree/shared/_login.html.erb

``` erb
<%= form_for Spree::User.new, :as => :spree_user, :url => spree.create_new_session_path, :format => :json, :remote => true do |f| %>
  <div id="password-credentials">
    <p>
      <%= f.label :email, Spree.t(:email) %><br />
      <%= f.email_field :email, :class => 'title', :tabindex => 1 %>
    </p>
    <p>
      <%= f.label :password, Spree.t(:password) %><br />
      <%= f.password_field :password, :class => 'title', :tabindex => 2 %>
    </p>
  </div>
  <p>
    <label>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me, Spree.t(:remember_me) %>
    </label>
  </p>

  <p><%= f.submit Spree.t(:login), :class => 'button primary', :tabindex => 3 %></p>
<% end %>
```

and respond to javascript in your controller.

**Comment by brendanhatton** [comment]
I also have this same issue - I would like to see a full working example if anyone has one available

**Comment by brendanhatton** [comment]
I found that having remote:true in the link_to_modal actually prevented the behaviour I would have expected. When I removed this, it seems that supplying a url (rather than a div) is sufficient to have the modal content load on ajax behaviour that I was looking for.

My link is now: 
<%= link_to_modal 'Contact Us', feedbacks_contact_path, :class=>"contact-link" %>
and the controller at the feedbacks_contact_path renders the contents of the modal window. Adding ':remote => true' to the form allows the submission to be ajax. I also realised there is a demo app included in the gem, and it some some working examples (but some which are no longer working also).
